# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Up',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('create', models.DateTimeField()),
                ('read', models.BooleanField(default=False)),
                ('url', models.CharField(max_length=255)),
                ('up', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notv.Up')),
            ],
        ),
    ]
