# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='up',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
