# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notv', '0003_auto_20160226_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='pic',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
