# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notv', '0004_auto_20160226_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='up',
            name='fromSite',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='video',
            name='create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
